### ISSUE TITLE
Feature request: Tree.create_from_hash()

### ISSUE THREAD

**Issue by markthomas** [evolve75/RubyTree#13]
I think RubyTree should have convenience methods to convert built-in hierarchical structures to trees. I propose `Tree.create_from_hash(hash)` as a class method. After all, you have JSON input/output, why not built-in data structures. I'd like for it to work with arbitrary nested hashes.

A few questions:
Is it OK as a class method? I think it makes sense.
Naming: do you prefer `Tree.create_from_hash()` or `Tree.from_hash()`?
Would you want it directly in the `Tree` class or split out into utility class like JSON is?

**Comment by joemsak** [comment]
So does this feature only work if all the final values are nil or a hash then? What about a real-world hash with data and content in it?

For example

```ruby
Tree::TreeNode.from_hash( {"en"=>
  {"courses"=>"Courses",
   "layouts"=>{"navigation"=>{"desktop"=>{"browse_courses"=>"Browse Courses", "this_one"=>false}}},
   "unrelated"=>{"dont"=>{"include"=>"this, please"}}}})

#=> ArgumentError: Invalid child. Must be nil or hash.
#=> from /app/RubyTree/lib/tree/utils/hash_converter.rb:106:in `from_hash'
```
