### ISSUE TITLE
find & findAll in tree

### ISSUE THREAD

**Issue by Kendos-Kenlen** [evolve75/RubyTree#54]
Hi,

Is there a way to find an item named `foo` in the tree and, if the `foo` item isn't unique, a method to find all of its occurrences ?

I need to create a dependency tree and because a dependency can exist multiple time, I need to find all it's occurrence to add it's dependencies.

**Comment by evolve75** [comment]
Hello @Kendos-Kenlen,

RubyTree actually mixes in the [Enumerable](http://ruby-doc.org/core-2.2.3/Enumerable.html) module, and hence the `find` and `find_all` methods are what you need.

Let me know if this works for you.

**Comment by Kendos-Kenlen** [comment]
Hi,

It's what I'm searching for, thank you ! :)
