### ISSUE TITLE
printTree OR print_tree?

### ISSUE THREAD

**Issue by Alexius-Huang** [evolve75/RubyTree#64]
Small issue. I try to use this method `print_tree` in my project, however, it just give me:

```
__path_name__/autoload.rb:28:in `<top (required)>': undefined method `print_tree' for #<Tree::TreeNode:0x007fedd91e8268> (NoMethodError)
Did you mean?  printTree
```

(Although I solved it just by changing to `printTree` method, however, the README should be updated OR according to the [Ruby style guide](https://github.com/bbatsov/ruby-style-guide#naming) it should be named as `print_tree`)

**Comment by marksiemers** [comment]
@evolve75 - This seems fixed to me, I just started using the gem, but I did not run into this issue.
