### ISSUE TITLE
calling 'protected' without arguments inside a method generates a StructuredWarnings::BuiltInWarning

### ISSUE THREAD

**Issue by cmtonkinson** [evolve75/RubyTree#70]
After upgrading my project to Ruby 2.7, the following warning is being emitted:

```/home/chris/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubytree-1.0.0/lib/tree/utils/camel_case_method_handler.rb:61:in `protected': calling protected without arguments inside a method may not have the intended effect (StructuredWarnings::BuiltInWarning)```

**Comment by joel** [comment]
@evolve75 do you mind pushing the 1.0.1 version on https://rubygems.org/gems/rubytree? Thanks 🙏

**Comment by cmtonkinson** [comment]
Bumping this @evolve75 - please and thank you!
