### ISSUE TITLE
camel_case_method_handler.rb generate warning in ruby 3.0.*

### ISSUE THREAD

**Issue by net1957** [evolve75/RubyTree#79]
I get this warning on ruby 3.0.* :

`Warning:[rake` --tasks] D:/program/dvlt/ruby/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rubytree-1.0.0/lib/tree/utils/camel_case_method_handler.rb:61:in `protected': warning: calling protected without arguments inside a method may not have the intended effect (StructuredWarnings::BuiltInWarning)`

Perhaps it would be possible to suppress the whole CamelCaseMethodHandler module? It is only needed to allow deprecated methods names.

Or simply replace 'protected' with 'protected `:to_snake_case'` ?

Cheers

**Comment by cmtonkinson** [comment]
@net1957 this was fixed in #71, if you update your Gemfile to pull `master` from git source rather than using a RubyGems tagged version the warning should go away.

**Comment by net1957** [comment]
I tried the latest master and it fix this error. Thank for this.
But it introduce a regression on json gem version.

 #fe8feb9 introduce this
 -  s.add_runtime_dependency 'json'                , '~> 2.1'
 +  s.add_runtime_dependency 'json'                , '~> 2.3.1'

so before this patch my application used json version 2.5 and after this patch I got 2.3.1
Could you change it to : 
  s.add_runtime_dependency 'json'                , '~> 2.3', '>=2.3.1'

**Comment by evolve75** [comment]
This issue has been fully resolved in Release 2.0.0.

See [R2.0.0 release notes](https://github.com/evolve75/RubyTree/releases/tag/R2.0.0) for details.
