### ISSUE TITLE
structured_warnings breaks Logger.warn

### ISSUE THREAD

**Issue by joegaudet** [evolve75/RubyTree#80]
The inclusion of structured_warnings breaks Logger#warn.

Seems sortof like bad form to include a library that monkey patches the standard library.

**Comment by delphaber** [comment]
I can confirm this behaviour too

**Comment by evolve75** [comment]
@joegaudet and @delphaber , happy to report that this issue has been fully resolved in Release 2.0.0.

See [R2.0.0 release notes](https://github.com/evolve75/RubyTree/releases/tag/R2.0.0) for details.

**Comment by delphaber** [comment]
Thank you!
