### ISSUE TITLE
Please release gem 1.0.1 for Ruby 2.7

### ISSUE THREAD

**Issue by cmtonkinson** [evolve75/RubyTree#81]
As requested per #70 kindly asking for a rubygems version `1.0.1` to publish fix for protected syntax warning.

**Comment by net1957** [comment]
It would be nice as master already  resolve it (by #71)!
It will also resolve #79 

in corporate environments it's not easy to use not released version of gems.

**Comment by rhatherall** [comment]
Is there any chance this will get released?

**Comment by evolve75** [comment]
Good news! Just released `1.0.2` that supports Ruby 2.7.

**Comment by rhatherall** [comment]
Thank you @evolve75 , that's great news!
