### ISSUE TITLE
Clarification of the used BSD licence

### ISSUE THREAD

**Issue by lindenthal** [evolve75/RubyTree#95]
Hi,

first of all thanks a lot for all the developers and maintainers of this gem.

I have a quick question regarding the [license](https://github.com/evolve75/RubyTree/blob/master/LICENSE.md) of this gem. In this repository you link to the [bsd-2-clause](https://opensource.org/license/bsd-2-clause/). On [Ruby Gems](https://rubygems.org/gems/rubytree) it states BSD-3-Clause-Clear.

I am not an license expert so please excuse a poentially stupid question: What is the correct license of the rubytree gem? And can you confirm that this is compatible with OpenProject that uses GPLv3?

Best regards and thanks a lot in advance
Niels

**Comment by lindenthal** [comment]
Thanks 👍 @evolve75

**Comment by sunpoet** [comment]
LICENSE.md is still 3-Clause BSD License.

**Comment by evolve75** [comment]
@sunpoet , thanks for pointing this out. Fixed in Release 2.0.2

**Comment by evolve75** [comment]
Retroactive note: this looks addressed by the BSD-license clarification work merged at https://github.com/evolve75/RubyTree/commit/31c4c6d .
The `next` branch later standardizes further on BSD-3-Clause, but this merge appears to be the issue-closing clarification step.
